### ISSUE TITLE
hi，有没有兴趣内置到我的create-cesium里呀？

### ISSUE THREAD

**Issue by nshen** [loosheng/d3tile-vue#1]
hi，大佬，我之前做了一个[create-cesium](https://github.com/nshen/create-cesium)， 运行 `yarn create cesium` 就可以方便的创建一个cesium 脚手架。看到你做了vue模板，但我不懂vue，不知道你有没有兴趣维护一个vue版本到create-cesium里？

**Comment by loosheng** [comment]
@nshen :) 这个项目不是模板，模板的话，我可以试着提供一下 `React` 与 `vue` 的版本
